let fakeData = [
    {
        "id": 1,
        "name": "agach",
        "enName": "english agach",
        "alName": "alman agach",
        "arName": "arab agach",
        "img": "https://i.ytimg.com/vi/NYilWKSfF_Y/mqdefault.jpg",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 2,
        "name": "laptop",
        "enName": "english laptop",
        "alName": "alman laptop",
        "arName": "arab laptop",
        "img": "",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 3,
        "name": "computer",
        "enName": "english computer",
        "alName": "alman computer",
        "arName": "arab computer",
        "img": "https://c.s-microsoft.com/en-ca/CMSImages/1920_Panel01_PriorityFeature_AIO.jpg?version=84488a58-c07f-6a34-a2f8-6c51a147d7fb",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 4,
        "name": "telefon",
        "enName": "english telefon",
        "alName": "alman telefon",
        "arName": "arab telefon",
        "img": "https://cdn.cimri.io/image/1200x1200/appleiphoneceptelefonlarfiyatlariphonemodelleri_178955480.jpg",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 5,
        "name": "pepsi",
        "enName": "english pepsi",
        "alName": "alman pepsi",
        "arName": "arab pepsi",
        "img": "",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 6,
        "name": "para",
        "enName": "english para",
        "alName": "alman para",
        "arName": "arab para",
        "img": "https://cdnntr1.img.sputniknews.com/img/07e4/0c/1e/1043488977_254:0:929:675_1920x0_80_0_0_069e4f2b1167dac9fd08e1a1d006d77c.jpg",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 7,
        "name": "kapi",
        "enName": "english kapi",
        "alName": "alman kapi",
        "arName": "arab kapi",
        "img": "",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 8,
        "name": "klavitura",
        "enName": "english klavitura",
        "alName": "alman klavitura",
        "arName": "arab klavitura",
        "img": "https://www.icover.ru/upload/resize_cache/iblock/9f6/1300_700_1/9f648d77e153f4c5db0babbd93ba0688.jpg",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 9,
        "name": "okul",
        "enName": "english okul",
        "alName": "alman okul",
        "arName": "arab okul",
        "img": "",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 10,
        "name": "asansor",
        "enName": "english asansor",
        "alName": "alman asansor",
        "arName": "arab asansor",
        "img": "https://www.betaasansor.com/statics/images/images-guvenli-asansorler-347.jpg",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        "id": 11,
        "name": "kahve",
        "enName": "english kahve",
        "alName": "alman kahve",
        "arName": "arab kahve",
        "img": "",
        "gif": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif",
        "date": '2022.30.05',
        "video": "https://videos.pond5.com/aerial-landscape-rainbow-mountain-peak-footage-116625631_main_xxl.mp4",
        "audio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "enaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "araudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        "alaudio": "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    }
];

export default fakeData;